# Generated by Django 3.0.4 on 2020-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
