# Generated by Django 3.0 on 2021-03-20 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wineapp', '0002_auto_20210320_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
