# Generated by Django 3.0 on 2021-03-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0003_wine_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'get_latest_by': 'posted_on', 'ordering': ['-id']},
        ),
    ]
