# Generated by Django 3.0.4 on 2020-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0003_auto_20200531_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
