# Generated by Django 3.0 on 2020-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0004_auto_20200531_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
