# Generated by Django 3.0 on 2020-09-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0005_auto_20200905_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
