# Generated by Django 3.0 on 2021-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0005_auto_20210417_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
