# Generated by Django 3.0 on 2021-07-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0005_auto_20210704_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='cellar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wineapp.Country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=models.ManyToManyField(blank=True, related_name='grape_set', to='wineapp.Grapes'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.ForeignKey(blank=True, default='', max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='wineapp.Type'),
        ),
    ]
