# Generated by Django 3.0 on 2021-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0006_auto_20210704_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=models.ManyToManyField(related_name='grape_set', to='wineapp.Grapes'),
        ),
    ]
