# Generated by Django 3.0 on 2020-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0007_auto_20200905_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
