# Generated by Django 3.0 on 2021-07-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0008_wine_closure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='wineapp.Type'),
        ),
    ]
