# Generated by Django 3.0 on 2021-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0009_auto_20210528_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
    ]
