# Generated by Django 3.0 on 2020-09-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0010_auto_20200921_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wineapp.Country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.ForeignKey(blank=True, default='', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='wineapp.Type'),
        ),
    ]
