# Generated by Django 3.0 on 2021-01-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0015_auto_20210110_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
