# Generated by Django 3.0 on 2021-01-15 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wineapp', '0016_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
