# Generated by Django 2.2.20 on 2021-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0017_auto_20210723_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='closure',
            field=models.CharField(choices=[('', 'Closure'), ('None', 'None'), ('Unknown', 'Unknown'), ('Agglomerate', 'Agglomerate'), ('Colmate', 'Colmate'), ('Diam', 'Diam'), ('Synthetic', 'Synthetic'), ('Natural', 'Natural'), ('Champagne', 'Champagne'), ('Crown cap', 'Crown cap'), ('Glass stopper', 'Glass stopper'), ('Helix', 'Helix'), ('Stopper cork', 'Stopper cork'), ('Screwcap', 'Screwcap'), ('Synthetic', 'Synthetic'), ('Twin top', 'Twin top'), ('Vinoseal/Vinolok', 'Vinoseal/Vinolok'), ('Zork', 'Zork')], max_length=100, null=True),
        ),
    ]
