# Generated by Django 2.2.20 on 2021-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0019_auto_20210731_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
