# Generated by Django 3.0 on 2021-01-16 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wineapp', '0019_auto_20210116_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
