# Generated by Django 4.0 on 2021-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0022_alter_comment_id_alter_country_id_alter_grapes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='bought_from',
            field=models.CharField(choices=[('', 'Bought From'), ('Bar/Restaurant', 'Bar/Restaurant'), ('Cellar Door', 'Cellar Door'), ('Gift', 'Gift'), ('Laithwaites', 'Laithwaites'), ('Local Independent', 'Local Independent'), ('Majestic Wines', 'Majestic Wines'), ('Online Auction', 'Online Auction'), ('Online Store', 'Online Store'), ('Other', 'Other'), ('Supermarket', 'Supermarket'), ('The Wine Society', 'The Wine Society'), ('Unknown', 'Unknown')], max_length=75, null=True),
        ),
    ]
